server:
  port: 8080
  servlet:
    context-path: /deutsch-hub

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/deutsch-hub}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:REMOVED_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

  mvc:
    locale: en