package com.deutschhub.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION("error.uncategorized", 9999),

    INVALID_USER_ID("error.shared.user.id.cannot.be.null", 1001),

    INVALID_EMAIL("error.identity.invalid.email", 3001),
    INVALID_ROLE_NAME("error.identity.invalid.role.name", 3002),
    INVALID_USERNAME("error.identity.invalid.username", 3003),
    INVALID_PASSWORD("error.identity.invalid.password", 3004),
    INVALID_FULL_NAME("error.identity.invalid.full.name", 3005),
    INVALID_CREDENTIALS("error.identity.invalid.credentials", 3006),

    USER_ALREADY_EXISTS("error.user.already.exists", 4001),
    USER_MUST_HAVE_AT_LEAST_ONE_ROLE("error.identity.user.must.have.at.least.one.role", 4002),
    USER_ALREADY_ACTIVE("error.identity.user.already.active", 4003),
    USER_ALREADY_DEACTIVATED("error.identity.user.already.deactivated", 4004),
    USER_DEACTIVATED("error.identity.user.deactivated", 4005),
    PASSWORD_ALREADY_USED("error.identity.password.already.used", 4006),
    EMAIL_ALREADY_USED("error.identity.email.already.used", 4007),
    EMAIL_ALREADY_EXISTS("error.identity.email.already.exists", 4008),
    USERNAME_ALREADY_EXISTS("error.identity.username.already.exists", 4009),
    USER_NOT_FOUND("error.identity.user.not.found", 4010),
    HASH_TOKEN_CAN_NOT_NULL("error.identity.hash.token.cannot.null", 4011),
    SESSION_ID_CAN_NOT_NULL("error.identity.session.id.cannot.null", 4012),
    INVALID_SESSION_TIME("error.identity.invalid.session.time", 4013),
    INVALID_SESSION_EXPIRATION("error.identity.invalid.session.expiration", 4014),
    SESSION_REVOKED("error.identity.session.revoked", 4015),
    SESSION_EXPIRED("error.identity.session.expired", 4016),
    CANNOT_DEACTIVATE_YOURSELF("error.identity.cannot.deactivate.yourself", 4017),
    CANNOT_REMOVE_YOUR_OWN_ADMIN_ROLE("error.identity.cannot.remove.your.own.admin.role", 4018),
    CURRENT_PASSWORD_INCORRECT("error.identity.current.password.incorrect", 4019),
    NEW_PASSWORD_MUST_BE_DIFFERENT("error.identity.new.password.must.be.different", 4020),
    PASSWORD_CONFIRMATION_NOT_MATCH("error.identity.password.confirmation.not.match", 4021),
    SESSION_NOT_FOUND("error.identity.session.not.found", 4022),
    INVALID_REFRESH_TOKEN("error.identity.refresh.token.invalid", 4107),
    USER_ID_CAN_NOT_NULL("error.identity.user.id.cannot.null", 40010),

    INVALID_COURSE_TITLE("error.course.invalid.title", 5001),
    INVALID_CEFR_LEVEL("error.course.invalid.level", 5002),
    INVALID_COURSE_PRICE("error.course.invalid.price", 5003),
    COURSE_HAS_NO_SECTIONS("error.course.has.no.sections", 5004),
    COURSE_ALREADY_PUBLISHED("error.course.already.published", 5005),
    CANNOT_MODIFY_PUBLISHED_COURSE("error.course.cannot.modify.published", 5006),
    INVALID_LESSON("error.course.invalid.lesson", 5007),
    INVALID_COURSE_INSTRUCTOR("error.course.invalid.instructor", 5008),
    COURSE_ALREADY_DELETED("error.course.already.deleted", 5009),
    COURSE_FORBIDDEN_ACTION("error.course.forbidden.action", 5010),
    COURSE_NOT_COMPLETED("error.course.not.completed", 5011),
    COURSE_NOT_FOUND("error.course.not.found", 5012),
    COURSE_NOT_PUBLISHED("error.learning.course.not.published",5013),
    COURSE_ACCESS_DENIED("error.course.access.denied", 5014),

    COURSE_MUST_HAVE_SECTION_BEFORE_PUBLISH("error.learning.course.must.have.section.before.publish", 50001),
    COURSE_MUST_HAVE_LESSON_BEFORE_PUBLISH("error.learning.course.must.have.lesson.before.publish", 50002),
    COURSE_ID_CAN_NOT_NULL("error.learning.course.id.can.not.null", 50003),
    COURSE_ALREADY_ENROLLED("error.learning.course.already.enrolled", 50004),


    INVALID_LESSON_ORDER("error.lesson.invalid.order", 6001),
    LESSON_INVALID_TITLE("error.lesson.invalid.title", 6002),
    LESSON_INVALID_DURATION("error.lesson.invalid.duration", 6003),
    LESSON_INVALID_CONTENT("error.lesson.invalid.content", 6004),
    LESSON_NOT_FOUND( "error.learning.lesson.not.found", 6005),
    INVALID_LESSON_TITLE("error.learning.lesson.invalid.title", 6006),
    INVALID_LESSON_MEDIA("error.learning.lesson.invalid.media", 6007),
    INVALID_LESSON_ESTIMATED_MINUTES( "error.learning.lesson.invalid.estimated.minutes", 6008),
    LESSON_ID_CAN_NOT_NULL("error.learning.lesson.id.can.not.null", 6009),
    LESSON_ALREADY_COMPLETED("error.learning.lesson.already.completed", 6010),

    SECTION_INVALID_TITLE("error.section.invalid.title", 7001),
    INVALID_SECTION_ORDER("error.section.invalid.order", 7002),
    SECTION_NOT_FOUND("error.section.not.found", 7003),

    INVALID_ENROLLMENT_DATA("error.enrollment.invalid.data", 8001),
    CANNOT_START_COMPLETED_ENROLLMENT("error.enrollment.cannot.start.completed", 8002),
    CANNOT_DROP_COMPLETED_ENROLLMENT("error.enrollment.cannot.drop.completed", 8003),
    INVALID_ENROLLMENT_STATE("error.enrollment.invalid.state", 8004),
    ENROLLMENT_NOT_ACTIVE("error.enrollment.not.active", 8005),
    ENROLLMENT_ALREADY_DELETED("error.enrollment.already.deleted", 8006),
    ENROLLMENT_FORBIDDEN_ACTION("error.enrollment.forbidden.action", 8007),
    INVALID_ENROLLMENT_STATUS( "error.enrollment.invalid.status",  8008),
    ENROLLMENT_NOT_FOUND( "error.enrollment.not.found", 8009),
    ENROLLMENT_ALREADY_COMPLETED("error.enrollment.already.completed", 8010),
    ENROLLMENT_ALREADY_DROPPED("error.enrollment.already.dropped", 8012),
    ENROLLMENT_EXPIRED("error.enrollment.expired", 8013),
    ENROLLMENT_CAN_NOT_BE_DROPPED("error.enrollment.can.not.be.dropped", 8014),
    ENROLLMENT_CAN_NOT_BE_EXPIRED("error.enrollment.can.not.expired", 8015),

    ENROLLMENT_PROGRESS_CANNOT_DECREASE("error.enrollment.progress.cannot.decrease", 8101),
    INVALID_ENROLLMENT_PROGRESS_STATE("error.enrollment.progress.state", 8102),

    ENROLLMENT_ID_CAN_NOT_NULL("error.learning.enrollment.id.can.not.null", 80001),

    INVALID_PROGRESS_DATA("error.enrollment.progress.invalid.data", 8103),

    INVALID_USER_PROGRESS_DATA("error.userprogress.invalid.data", 9001),
    USER_PROGRESS_ALREADY_COMPLETED("error.userprogress.already.completed", 9002),
    USER_PROGRESS_ALREADY_DELETED("error.userprogress.already.deleted", 9003),
    USER_PROGRESS_FORBIDDEN_ACTION("error.userprogress.forbidden.action", 9004),
    PROGRESS_CANNOT_DECREASE("error.userprogress.progress.cannot.decrease", 9101),


    QUIZ_INVALID_TITLE("error.quiz.invalid.title", 10001),
    QUIZ_INVALID_TIME_LIMIT("error.quiz.invalid.time.limit", 10002),
    QUIZ_INVALID_MAX_SCORE("error.quiz.invalid.max.score", 10003),
    QUIZ_INVALID_PASSING_SCORE("error.quiz.invalid.passing.score", 10004),
    QUIZ_HAS_NO_QUESTIONS("error.quiz.has.no.questions", 10005),
    QUIZ_ALREADY_PUBLISHED("error.quiz.already.published", 10006),
    CANNOT_MODIFY_PUBLISHED_QUIZ("error.quiz.cannot.modify.published", 10007),
    INVALID_QUESTION("error.quiz.invalid.question", 10008),
    QUIZ_SCORE_MISMATCH("error.quiz.score.mismatch", 10009),
    INVALID_QUIZ_STATE("error.quiz.invalid.state", 10010),
    QUIZ_SCORE_EXCEEDS_MAX("error.quiz.score.exceeds.max", 10011),
    QUIZ_ALREADY_DELETED("error.quiz.already.deleted", 10012),
    QUIZ_REQUIREMENT_NOT_MET("error.quiz.requirement.not.met", 10013),
    QUIZ_FORBIDDEN_ACTION("error.quiz.forbidden.action", 10014),

    INVALID_QUESTION_CONTENT("error.question.invalid.content", 11001),
    INVALID_QUESTION_SCORE("error.question.invalid.score", 11002),
    QUESTION_NOT_ENOUGH_ANSWERS("error.question.not.enough.answers", 11003),
    QUESTION_NO_CORRECT_ANSWER("error.question.no.correct.answer", 11004),
    QUESTION_TOO_MANY_CORRECT_ANSWERS("error.question.too.many.correct.answers", 11005),
    QUESTION_NOT_FOUND("error.question.not.found", 11006),
    DUPLICATE_ANSWER("error.question.answer.duplicate", 11007),
    QUESTION_TRUE_FALSE_INVALID("error.question.truefalse.invalid", 11008),
    INVALID_ANSWER("error.question.answer.invalid", 11101),
    ANSWER_NOT_FOUND("error.question.answer.not.found", 11102),
    TOO_MANY_ANSWERS("error.question.answer.too.many", 11103),
    QUESTION_NOT_BELONG_TO_QUIZ("error.question.not.belong.to.quiz", 11104),

    INVALID_QUIZ_ATTEMPT_DATA("error.quiz.attempt.invalid.data", 12001),
    QUIZ_ATTEMPT_EMPTY("error.quiz.attempt.empty", 12002),
    INVALID_QUIZ_ATTEMPT_STATE("error.quiz.attempt.invalid.state", 12003),
    QUIZ_ATTEMPT_ALREADY_DELETED("error.quiz.attempt.already.deleted", 12004),
    QUIZ_ATTEMPT_NOT_ALL_ANSWERED("error.quiz.attempt.not.all.answered", 12005),
    QUIZ_ATTEMPT_FORBIDDEN_ACTION("error.quiz.attempt.forbidden.action", 12006),
    INVALID_USER_ANSWER("error.user.answer.invalid", 12101),
    INVALID_USER_ANSWER_DATA("error.user.answer.invalid.data", 12102),

    CERTIFICATE_FORBIDDEN_ACTION("error.certificate.forbidden.action", 13001),

    LESSON_COMPLETION_ID_CAN_NOT_NULL("error.learning.lesson.completion.id.can.not.null", 14001),

    INVALID_MEDIA_FILE_NAME("error.media.invalid.file.name", 15001),
    INVALID_MEDIA_STORAGE_KEY("error.media.invalid.storage.key", 15002),
    INVALID_MEDIA_TYPE("error.media.invalid.type", 15003),
    INVALID_MEDIA_MIME_TYPE("error.media.invalid.mime.type", 15004),
    INVALID_MEDIA_SIZE("error.media.invalid.size", 15005),
    INVALID_MEDIA_CREATED_AT("error.media.invalid.created.at", 15006),
    INVALID_MEDIA_UPLOAD("error.media.invalid.upload", 15007),
    MEDIA_FILE_TOO_LARGE("error.media.file.too.large", 15008),
    MEDIA_NOT_FOUND("error.media.not.found", 15009),
    MEDIA_OWNER_CAN_NOT_NULL("error.media.owner.can.not.null", 15010),
    MEDIA_ACCESS_DENIED("error.media.access.denied", 15011),

    MEDIA_ID_CAN_NOT_NULL("error.media.id.can.not.null", 15101),
    MEDIA_UPLOADER_CAN_NOT_NULL("error.media.uploader.can.not.null", 15102),

    LESSON_ITEM_NOT_FOUND("error.lesson.item.not.found", 16000),
    LESSON_ITEM_MEDIA_NOT_FOUND("error.lesson.item.media.not.found", 16001),


    INVALID_ARTICLE_VERSION_NUMBER("error.content.article.invalid.version.number", 17000),
    INVALID_SOURCE_TITLE("error.content.article.invalid.source.title", 17006),
    INVALID_SOURCE_URL("error.content.article.invalid.source.url", 17007),
    INVALID_ARTICLE_TITLE("error.content.article.invalid.title", 17008),
    INVALID_ARTICLE_SUMMARY("error.content.article.invalid.summary", 17009),
    INVALID_ARTICLE_BODY("error.content.article.invalid.body", 17010),
    INVALID_ARTICLE_SLUG("error.content.article.invalid.slug", 17011),
    INVALID_REVIEW_FEEDBACK("error.content.article.review.feedback.invalid", 17012),
    INVALID_REVIEW_STATE("error.content.article.review.invalid.state", 17013),
    ARTICLE_DRAFT_NOT_EDITABLE("error.content.article.draft.not.editable", 17014),
    ARTICLE_DRAFT_VERSION_NOT_FOUND("error.content.article.draft.version.not.found", 17015),
    INVALID_ARTICLE_COLLECTION("error.content.article.collection.invalid", 17016),
    ARTICLE_CAN_NOT_SUBMIT_REVIEW("error.content.article.cannot.submit.review", 17017),
    ARTICLE_DRAFT_INCOMPLETE("error.content.article.draft.incomplete", 17018),
    INVALID_REVIEW_CYCLE("error.content.article.review.cycle.invalid", 17019),
    ARTICLE_NOT_OWNED_BY_ACTOR("error.content.article.not.owned.by.actor", 17020),
    INVALID_ARTICLE_DATA("error.content.article.invalid.data", 17021),
    INVALID_ARTICLE_VERSION_DATA("error.content.article.version.invalid.data", 17022),
    INVALID_REVIEW_CYCLE_DATA("error.content.article.review.cycle.invalid.data", 17023),
    ARTICLE_REVIEW_NOT_IN_PROGRESS("error.content.article.review.not.in.progress", 17024),
    ARTICLE_REVIEW_CYCLE_NOT_FOUND("error.content.article.review.cycle.not.found", 17025),
    ARTICLE_REVIEW_ALREADY_PENDING("error.content.article.review.already.pending", 17026),
    INVALID_ARTICLE_PUBLICATION_DATA("error.content.article.publication.invalid.data", 17027),
    ARTICLE_NEW_DRAFT_NOT_ALLOWED("error.content.article.new.draft.not.allowed", 17028),
    ARTICLE_PUBLISHED_VERSION_NOT_FOUND("error.content.article.published.version.not.found", 17029),
    ARTICLE_DRAFT_ALREADY_EXISTS("error.content.article.draft.already.exists", 17030),
    INVALID_ARTICLE_ARCHIVE_DATA("error.content.article.archive.invalid.data", 17031),
    ARTICLE_CAN_NOT_ARCHIVE("error.content.article.cannot.archive", 17032),
    INVALID_ARTICLE_OWNER("error.content.article.owner.invalid", 17033),
    INVALID_ARTICLE_OWNERSHIP_TRANSFER_DATA("error.content.article.ownership.transfer.invalid.data", 17034),
    ARTICLE_OWNERSHIP_TRANSFER_NOT_ALLOWED("error.content.article.ownership.transfer.not.allowed", 17035),
    ARTICLE_ALREADY_OWNED_BY_ACTOR("error.content.article.already.owned.by.actor", 17036),
    INVALID_REVIEW_COMPLETION_DATA("error.content.article.review.completion.invalid.data", 17037),
    INVALID_REVIEW_RESULT("error.content.article.review.result.invalid", 17038),
    INVALID_REVIEW_WITHDRAWAL_DATA("error.content.article.review.withdrawal.invalid.data", 17039),
    ARTICLE_SLUG_ALREADY_EXISTS("error.content.article.slug.already.exists", 17040),
    ARTICLE_NOT_FOUND("error.content.article.not.found", 17041),
    INVALID_ARTICLE_NEW_OWNER("error.content.article.new.owner.invalid", 17042),
    ARTICLE_ARCHIVED("error.content.article.archived", 17043),

    INVALID_CATEGORY_NAME("error.content.category.name.invalid", 18000),
    CATEGORY_ALREADY_INACTIVE("error.content.category.already.inactive", 18001),
    CATEGORY_ALREADY_ACTIVE("error.content.category.already.active", 18002),
    INVALID_CATEGORY_DATA("error.content.category.invalid.data", 18003),
    INVALID_CATEGORY_STATUS("error.content.category.status.invalid", 18004),
    CATEGORY_NAME_ALREADY_EXISTS("error.content.category.name.already.exists", 18005),
    CATEGORY_NOT_FOUND("error.content.category.not.found", 18006),
    CATEGORY_NOT_ACTIVE("error.content.category.not.active", 18007),

    INVALID_TOPIC_NAME("error.content.topic.name.invalid", 19000),
    INVALID_TOPIC_CATEGORY("error.content.topic.category.invalid", 19001),
    TOPIC_ALREADY_INACTIVE("error.content.topic.already.inactive", 19002),
    TOPIC_ALREADY_ACTIVE("error.content.topic.already.active", 19003),
    INVALID_TOPIC_DATA("error.content.topic.invalid.data", 19004),
    INVALID_TOPIC_STATUS("error.content.topic.status.invalid", 19005),
    TOPIC_NAME_ALREADY_EXISTS("error.content.topic.name.already.exists", 19006),
    TOPIC_NOT_FOUND("error.content.topic.not.found", 19007),
    TOPIC_NOT_ACTIVE("error.content.topic.not.active", 19008),
    TOPIC_NOT_BELONG_TO_CATEGORY("error.content.topic.not.belong.to.category", 19009),

    CONTENT_FORBIDDEN_ACTION("error.content.forbidden.action", 20000),
    MEDIA_NOT_SUITABLE_FOR_COVER("error.content.media.not.suitable.for.cover", 20001),

    ;

    private final String messageKey;
    private final int errorCode;

    ErrorCode(String messageKey, int errorCode) {
        this.messageKey = messageKey;
        this.errorCode = errorCode;
    }

}
