package com.deutschhub.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION("error.uncategorized", 9999, ErrorHttpStatus.INTERNAL_SERVER_ERROR),

    INVALID_USER_ID("error.shared.user.id.cannot.be.null", 1001, ErrorHttpStatus.BAD_REQUEST),
    ACCESS_DENIED("error.shared.access.denied", 1002, ErrorHttpStatus.FORBIDDEN),
    RESOURCE_VERSION_CONFLICT("error.common.resource.version.conflict", 1003, ErrorHttpStatus.CONFLICT),

    INVALID_EMAIL("error.identity.invalid.email", 3001, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ROLE_NAME("error.identity.invalid.role.name", 3002, ErrorHttpStatus.BAD_REQUEST),
    INVALID_USERNAME("error.identity.invalid.username", 3003, ErrorHttpStatus.BAD_REQUEST),
    INVALID_PASSWORD("error.identity.invalid.password", 3004, ErrorHttpStatus.BAD_REQUEST),
    INVALID_FULL_NAME("error.identity.invalid.full.name", 3005, ErrorHttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS("error.identity.invalid.credentials", 3006, ErrorHttpStatus.UNAUTHORIZED),

    USER_ALREADY_EXISTS("error.user.already.exists", 4001, ErrorHttpStatus.CONFLICT),
    USER_MUST_HAVE_AT_LEAST_ONE_ROLE("error.identity.user.must.have.at.least.one.role", 4002, ErrorHttpStatus.BAD_REQUEST),
    USER_ALREADY_ACTIVE("error.identity.user.already.active", 4003, ErrorHttpStatus.CONFLICT),
    USER_ALREADY_DEACTIVATED("error.identity.user.already.deactivated", 4004, ErrorHttpStatus.CONFLICT),
    USER_DEACTIVATED("error.identity.user.deactivated", 4005, ErrorHttpStatus.FORBIDDEN),
    PASSWORD_ALREADY_USED("error.identity.password.already.used", 4006, ErrorHttpStatus.CONFLICT),
    EMAIL_ALREADY_USED("error.identity.email.already.used", 4007, ErrorHttpStatus.CONFLICT),
    EMAIL_ALREADY_EXISTS("error.identity.email.already.exists", 4008, ErrorHttpStatus.CONFLICT),
    USERNAME_ALREADY_EXISTS("error.identity.username.already.exists", 4009, ErrorHttpStatus.CONFLICT),
    USER_NOT_FOUND("error.identity.user.not.found", 4010, ErrorHttpStatus.NOT_FOUND),
    HASH_TOKEN_CAN_NOT_NULL("error.identity.hash.token.cannot.null", 4011, ErrorHttpStatus.BAD_REQUEST),
    SESSION_ID_CAN_NOT_NULL("error.identity.session.id.cannot.null", 4012, ErrorHttpStatus.BAD_REQUEST),
    INVALID_SESSION_TIME("error.identity.invalid.session.time", 4013, ErrorHttpStatus.BAD_REQUEST),
    INVALID_SESSION_EXPIRATION("error.identity.invalid.session.expiration", 4014, ErrorHttpStatus.BAD_REQUEST),
    SESSION_REVOKED("error.identity.session.revoked", 4015, ErrorHttpStatus.UNAUTHORIZED),
    SESSION_EXPIRED("error.identity.session.expired", 4016, ErrorHttpStatus.UNAUTHORIZED),
    CANNOT_DEACTIVATE_YOURSELF("error.identity.cannot.deactivate.yourself", 4017, ErrorHttpStatus.FORBIDDEN),
    CANNOT_REMOVE_YOUR_OWN_ADMIN_ROLE("error.identity.cannot.remove.your.own.admin.role", 4018, ErrorHttpStatus.FORBIDDEN),
    CURRENT_PASSWORD_INCORRECT("error.identity.current.password.incorrect", 4019, ErrorHttpStatus.BAD_REQUEST),
    NEW_PASSWORD_MUST_BE_DIFFERENT("error.identity.new.password.must.be.different", 4020, ErrorHttpStatus.BAD_REQUEST),
    PASSWORD_CONFIRMATION_NOT_MATCH("error.identity.password.confirmation.not.match", 4021, ErrorHttpStatus.BAD_REQUEST),
    SESSION_NOT_FOUND("error.identity.session.not.found", 4022, ErrorHttpStatus.NOT_FOUND),
    INVALID_REFRESH_TOKEN("error.identity.refresh.token.invalid", 4107, ErrorHttpStatus.UNAUTHORIZED),
    USER_ID_CAN_NOT_NULL("error.identity.user.id.cannot.null", 40010, ErrorHttpStatus.BAD_REQUEST),

    INVALID_COURSE_TITLE("error.course.invalid.title", 5001, ErrorHttpStatus.BAD_REQUEST),
    INVALID_CEFR_LEVEL("error.course.invalid.level", 5002, ErrorHttpStatus.BAD_REQUEST),
    INVALID_COURSE_PRICE("error.course.invalid.price", 5003, ErrorHttpStatus.BAD_REQUEST),
    COURSE_HAS_NO_SECTIONS("error.course.has.no.sections", 5004, ErrorHttpStatus.BAD_REQUEST),
    COURSE_ALREADY_PUBLISHED("error.course.already.published", 5005, ErrorHttpStatus.CONFLICT),
    CANNOT_MODIFY_PUBLISHED_COURSE("error.course.cannot.modify.published", 5006, ErrorHttpStatus.CONFLICT),
    INVALID_LESSON("error.course.invalid.lesson", 5007, ErrorHttpStatus.BAD_REQUEST),
    INVALID_COURSE_INSTRUCTOR("error.course.invalid.instructor", 5008, ErrorHttpStatus.BAD_REQUEST),
    COURSE_ALREADY_DELETED("error.course.already.deleted", 5009, ErrorHttpStatus.CONFLICT),
    COURSE_FORBIDDEN_ACTION("error.course.forbidden.action", 5010, ErrorHttpStatus.FORBIDDEN),
    COURSE_NOT_COMPLETED("error.course.not.completed", 5011, ErrorHttpStatus.BAD_REQUEST),
    COURSE_NOT_FOUND("error.course.not.found", 5012, ErrorHttpStatus.NOT_FOUND),
    COURSE_NOT_PUBLISHED("error.learning.course.not.published", 5013, ErrorHttpStatus.NOT_FOUND),
    COURSE_ACCESS_DENIED("error.course.access.denied", 5014, ErrorHttpStatus.FORBIDDEN),

    COURSE_MUST_HAVE_SECTION_BEFORE_PUBLISH("error.learning.course.must.have.section.before.publish", 50001, ErrorHttpStatus.BAD_REQUEST),
    COURSE_MUST_HAVE_LESSON_BEFORE_PUBLISH("error.learning.course.must.have.lesson.before.publish", 50002, ErrorHttpStatus.BAD_REQUEST),
    COURSE_ID_CAN_NOT_NULL("error.learning.course.id.can.not.null", 50003, ErrorHttpStatus.BAD_REQUEST),
    COURSE_ALREADY_ENROLLED("error.learning.course.already.enrolled", 50004, ErrorHttpStatus.CONFLICT),

    INVALID_LESSON_ORDER("error.lesson.invalid.order", 6001, ErrorHttpStatus.BAD_REQUEST),
    LESSON_INVALID_TITLE("error.lesson.invalid.title", 6002, ErrorHttpStatus.BAD_REQUEST),
    LESSON_INVALID_DURATION("error.lesson.invalid.duration", 6003, ErrorHttpStatus.BAD_REQUEST),
    LESSON_INVALID_CONTENT("error.lesson.invalid.content", 6004, ErrorHttpStatus.BAD_REQUEST),
    LESSON_NOT_FOUND("error.learning.lesson.not.found", 6005, ErrorHttpStatus.NOT_FOUND),
    INVALID_LESSON_TITLE("error.learning.lesson.invalid.title", 6006, ErrorHttpStatus.BAD_REQUEST),
    INVALID_LESSON_MEDIA("error.learning.lesson.invalid.media", 6007, ErrorHttpStatus.BAD_REQUEST),
    INVALID_LESSON_ESTIMATED_MINUTES("error.learning.lesson.invalid.estimated.minutes", 6008, ErrorHttpStatus.BAD_REQUEST),
    LESSON_ID_CAN_NOT_NULL("error.learning.lesson.id.can.not.null", 6009, ErrorHttpStatus.BAD_REQUEST),
    LESSON_ALREADY_COMPLETED("error.learning.lesson.already.completed", 6010, ErrorHttpStatus.CONFLICT),

    SECTION_INVALID_TITLE("error.section.invalid.title", 7001, ErrorHttpStatus.BAD_REQUEST),
    INVALID_SECTION_ORDER("error.section.invalid.order", 7002, ErrorHttpStatus.BAD_REQUEST),
    SECTION_NOT_FOUND("error.section.not.found", 7003, ErrorHttpStatus.NOT_FOUND),

    INVALID_ENROLLMENT_DATA("error.enrollment.invalid.data", 8001, ErrorHttpStatus.BAD_REQUEST),
    CANNOT_START_COMPLETED_ENROLLMENT("error.enrollment.cannot.start.completed", 8002, ErrorHttpStatus.CONFLICT),
    CANNOT_DROP_COMPLETED_ENROLLMENT("error.enrollment.cannot.drop.completed", 8003, ErrorHttpStatus.CONFLICT),
    INVALID_ENROLLMENT_STATE("error.enrollment.invalid.state", 8004, ErrorHttpStatus.BAD_REQUEST),
    ENROLLMENT_NOT_ACTIVE("error.enrollment.not.active", 8005, ErrorHttpStatus.CONFLICT),
    ENROLLMENT_ALREADY_DELETED("error.enrollment.already.deleted", 8006, ErrorHttpStatus.CONFLICT),
    ENROLLMENT_FORBIDDEN_ACTION("error.enrollment.forbidden.action", 8007, ErrorHttpStatus.FORBIDDEN),
    INVALID_ENROLLMENT_STATUS("error.enrollment.invalid.status", 8008, ErrorHttpStatus.BAD_REQUEST),
    ENROLLMENT_NOT_FOUND("error.enrollment.not.found", 8009, ErrorHttpStatus.NOT_FOUND),
    ENROLLMENT_ALREADY_COMPLETED("error.enrollment.already.completed", 8010, ErrorHttpStatus.CONFLICT),
    ENROLLMENT_ALREADY_DROPPED("error.enrollment.already.dropped", 8012, ErrorHttpStatus.CONFLICT),
    ENROLLMENT_EXPIRED("error.enrollment.expired", 8013, ErrorHttpStatus.GONE),
    ENROLLMENT_CAN_NOT_BE_DROPPED("error.enrollment.can.not.be.dropped", 8014, ErrorHttpStatus.CONFLICT),
    ENROLLMENT_CAN_NOT_BE_EXPIRED("error.enrollment.can.not.expired", 8015, ErrorHttpStatus.CONFLICT),

    ENROLLMENT_PROGRESS_CANNOT_DECREASE("error.enrollment.progress.cannot.decrease", 8101, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ENROLLMENT_PROGRESS_STATE("error.enrollment.progress.state", 8102, ErrorHttpStatus.BAD_REQUEST),

    ENROLLMENT_ID_CAN_NOT_NULL("error.learning.enrollment.id.can.not.null", 80001, ErrorHttpStatus.BAD_REQUEST),

    INVALID_PROGRESS_DATA("error.enrollment.progress.invalid.data", 8103, ErrorHttpStatus.BAD_REQUEST),

    INVALID_USER_PROGRESS_DATA("error.userprogress.invalid.data", 9001, ErrorHttpStatus.BAD_REQUEST),
    USER_PROGRESS_ALREADY_COMPLETED("error.userprogress.already.completed", 9002, ErrorHttpStatus.CONFLICT),
    USER_PROGRESS_ALREADY_DELETED("error.userprogress.already.deleted", 9003, ErrorHttpStatus.CONFLICT),
    USER_PROGRESS_FORBIDDEN_ACTION("error.userprogress.forbidden.action", 9004, ErrorHttpStatus.FORBIDDEN),
    PROGRESS_CANNOT_DECREASE("error.userprogress.progress.cannot.decrease", 9101, ErrorHttpStatus.BAD_REQUEST),

    QUIZ_INVALID_TITLE("error.quiz.invalid.title", 10001, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_INVALID_TIME_LIMIT("error.quiz.invalid.time.limit", 10002, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_INVALID_MAX_SCORE("error.quiz.invalid.max.score", 10003, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_INVALID_PASSING_SCORE("error.quiz.invalid.passing.score", 10004, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_HAS_NO_QUESTIONS("error.quiz.has.no.questions", 10005, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_ALREADY_PUBLISHED("error.quiz.already.published", 10006, ErrorHttpStatus.CONFLICT),
    CANNOT_MODIFY_PUBLISHED_QUIZ("error.quiz.cannot.modify.published", 10007, ErrorHttpStatus.CONFLICT),
    INVALID_QUESTION("error.quiz.invalid.question", 10008, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_SCORE_MISMATCH("error.quiz.score.mismatch", 10009, ErrorHttpStatus.BAD_REQUEST),
    INVALID_QUIZ_STATE("error.quiz.invalid.state", 10010, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_SCORE_EXCEEDS_MAX("error.quiz.score.exceeds.max", 10011, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_ALREADY_DELETED("error.quiz.already.deleted", 10012, ErrorHttpStatus.CONFLICT),
    QUIZ_REQUIREMENT_NOT_MET("error.quiz.requirement.not.met", 10013, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_FORBIDDEN_ACTION("error.quiz.forbidden.action", 10014, ErrorHttpStatus.FORBIDDEN),

    INVALID_QUESTION_CONTENT("error.question.invalid.content", 11001, ErrorHttpStatus.BAD_REQUEST),
    INVALID_QUESTION_SCORE("error.question.invalid.score", 11002, ErrorHttpStatus.BAD_REQUEST),
    QUESTION_NOT_ENOUGH_ANSWERS("error.question.not.enough.answers", 11003, ErrorHttpStatus.BAD_REQUEST),
    QUESTION_NO_CORRECT_ANSWER("error.question.no.correct.answer", 11004, ErrorHttpStatus.BAD_REQUEST),
    QUESTION_TOO_MANY_CORRECT_ANSWERS("error.question.too.many.correct.answers", 11005, ErrorHttpStatus.BAD_REQUEST),
    QUESTION_NOT_FOUND("error.question.not.found", 11006, ErrorHttpStatus.NOT_FOUND),
    DUPLICATE_ANSWER("error.question.answer.duplicate", 11007, ErrorHttpStatus.CONFLICT),
    QUESTION_TRUE_FALSE_INVALID("error.question.truefalse.invalid", 11008, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ANSWER("error.question.answer.invalid", 11101, ErrorHttpStatus.BAD_REQUEST),
    ANSWER_NOT_FOUND("error.question.answer.not.found", 11102, ErrorHttpStatus.NOT_FOUND),
    TOO_MANY_ANSWERS("error.question.answer.too.many", 11103, ErrorHttpStatus.BAD_REQUEST),
    QUESTION_NOT_BELONG_TO_QUIZ("error.question.not.belong.to.quiz", 11104, ErrorHttpStatus.BAD_REQUEST),

    INVALID_QUIZ_ATTEMPT_DATA("error.quiz.attempt.invalid.data", 12001, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_ATTEMPT_EMPTY("error.quiz.attempt.empty", 12002, ErrorHttpStatus.BAD_REQUEST),
    INVALID_QUIZ_ATTEMPT_STATE("error.quiz.attempt.invalid.state", 12003, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_ATTEMPT_ALREADY_DELETED("error.quiz.attempt.already.deleted", 12004, ErrorHttpStatus.CONFLICT),
    QUIZ_ATTEMPT_NOT_ALL_ANSWERED("error.quiz.attempt.not.all.answered", 12005, ErrorHttpStatus.BAD_REQUEST),
    QUIZ_ATTEMPT_FORBIDDEN_ACTION("error.quiz.attempt.forbidden.action", 12006, ErrorHttpStatus.FORBIDDEN),
    INVALID_USER_ANSWER("error.user.answer.invalid", 12101, ErrorHttpStatus.BAD_REQUEST),
    INVALID_USER_ANSWER_DATA("error.user.answer.invalid.data", 12102, ErrorHttpStatus.BAD_REQUEST),

    CERTIFICATE_FORBIDDEN_ACTION("error.certificate.forbidden.action", 13001, ErrorHttpStatus.FORBIDDEN),

    LESSON_COMPLETION_ID_CAN_NOT_NULL("error.learning.lesson.completion.id.can.not.null", 14001, ErrorHttpStatus.BAD_REQUEST),

    INVALID_MEDIA_FILE_NAME("error.media.invalid.file.name", 15001, ErrorHttpStatus.BAD_REQUEST),
    INVALID_MEDIA_STORAGE_KEY("error.media.invalid.storage.key", 15002, ErrorHttpStatus.BAD_REQUEST),
    INVALID_MEDIA_TYPE("error.media.invalid.type", 15003, ErrorHttpStatus.BAD_REQUEST),
    INVALID_MEDIA_MIME_TYPE("error.media.invalid.mime.type", 15004, ErrorHttpStatus.BAD_REQUEST),
    INVALID_MEDIA_SIZE("error.media.invalid.size", 15005, ErrorHttpStatus.BAD_REQUEST),
    INVALID_MEDIA_CREATED_AT("error.media.invalid.created.at", 15006, ErrorHttpStatus.BAD_REQUEST),
    INVALID_MEDIA_UPLOAD("error.media.invalid.upload", 15007, ErrorHttpStatus.BAD_REQUEST),
    MEDIA_FILE_TOO_LARGE("error.media.file.too.large", 15008, ErrorHttpStatus.BAD_REQUEST),
    MEDIA_NOT_FOUND("error.media.not.found", 15009, ErrorHttpStatus.NOT_FOUND),
    MEDIA_OWNER_CAN_NOT_NULL("error.media.owner.can.not.null", 15010, ErrorHttpStatus.BAD_REQUEST),
    MEDIA_ACCESS_DENIED("error.media.access.denied", 15011, ErrorHttpStatus.FORBIDDEN),
    MEDIA_ID_CAN_NOT_NULL("error.media.id.can.not.null", 15101, ErrorHttpStatus.BAD_REQUEST),
    MEDIA_UPLOADER_CAN_NOT_NULL("error.media.uploader.can.not.null", 15102, ErrorHttpStatus.BAD_REQUEST),

    LESSON_ITEM_NOT_FOUND("error.lesson.item.not.found", 16000, ErrorHttpStatus.NOT_FOUND),
    LESSON_ITEM_MEDIA_NOT_FOUND("error.lesson.item.media.not.found", 16001, ErrorHttpStatus.NOT_FOUND),

    INVALID_ARTICLE_VERSION_NUMBER("error.content.article.invalid.version.number", 17000, ErrorHttpStatus.BAD_REQUEST),
    INVALID_SOURCE_TITLE("error.content.article.invalid.source.title", 17006, ErrorHttpStatus.BAD_REQUEST),
    INVALID_SOURCE_URL("error.content.article.invalid.source.url", 17007, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ARTICLE_TITLE("error.content.article.invalid.title", 17008, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ARTICLE_SUMMARY("error.content.article.invalid.summary", 17009, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ARTICLE_BODY("error.content.article.invalid.body", 17010, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ARTICLE_SLUG("error.content.article.invalid.slug", 17011, ErrorHttpStatus.BAD_REQUEST),
    INVALID_REVIEW_FEEDBACK("error.content.article.review.feedback.invalid", 17012, ErrorHttpStatus.BAD_REQUEST),
    INVALID_REVIEW_STATE("error.content.article.review.invalid.state", 17013, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_DRAFT_NOT_EDITABLE("error.content.article.draft.not.editable", 17014, ErrorHttpStatus.CONFLICT),
    ARTICLE_DRAFT_VERSION_NOT_FOUND("error.content.article.draft.version.not.found", 17015, ErrorHttpStatus.NOT_FOUND),
    INVALID_ARTICLE_COLLECTION("error.content.article.collection.invalid", 17016, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_CAN_NOT_SUBMIT_REVIEW("error.content.article.cannot.submit.review", 17017, ErrorHttpStatus.CONFLICT),
    ARTICLE_DRAFT_INCOMPLETE("error.content.article.draft.incomplete", 17018, ErrorHttpStatus.BAD_REQUEST),
    INVALID_REVIEW_CYCLE("error.content.article.review.cycle.invalid", 17019, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_NOT_OWNED_BY_ACTOR("error.content.article.not.owned.by.actor", 17020, ErrorHttpStatus.FORBIDDEN),
    INVALID_ARTICLE_DATA("error.content.article.invalid.data", 17021, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ARTICLE_VERSION_DATA("error.content.article.version.invalid.data", 17022, ErrorHttpStatus.BAD_REQUEST),
    INVALID_REVIEW_CYCLE_DATA("error.content.article.review.cycle.invalid.data", 17023, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_REVIEW_NOT_IN_PROGRESS("error.content.article.review.not.in.progress", 17024, ErrorHttpStatus.CONFLICT),
    ARTICLE_REVIEW_CYCLE_NOT_FOUND("error.content.article.review.cycle.not.found", 17025, ErrorHttpStatus.NOT_FOUND),
    ARTICLE_REVIEW_ALREADY_PENDING("error.content.article.review.already.pending", 17026, ErrorHttpStatus.CONFLICT),
    INVALID_ARTICLE_PUBLICATION_DATA("error.content.article.publication.invalid.data", 17027, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_NEW_DRAFT_NOT_ALLOWED("error.content.article.new.draft.not.allowed", 17028, ErrorHttpStatus.CONFLICT),
    ARTICLE_PUBLISHED_VERSION_NOT_FOUND("error.content.article.published.version.not.found", 17029, ErrorHttpStatus.NOT_FOUND),
    ARTICLE_DRAFT_ALREADY_EXISTS("error.content.article.draft.already.exists", 17030, ErrorHttpStatus.CONFLICT),
    INVALID_ARTICLE_ARCHIVE_DATA("error.content.article.archive.invalid.data", 17031, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_CAN_NOT_ARCHIVE("error.content.article.cannot.archive", 17032, ErrorHttpStatus.CONFLICT),
    INVALID_ARTICLE_OWNER("error.content.article.owner.invalid", 17033, ErrorHttpStatus.BAD_REQUEST),
    INVALID_ARTICLE_OWNERSHIP_TRANSFER_DATA("error.content.article.ownership.transfer.invalid.data", 17034, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_OWNERSHIP_TRANSFER_NOT_ALLOWED("error.content.article.ownership.transfer.not.allowed", 17035, ErrorHttpStatus.CONFLICT),
    ARTICLE_ALREADY_OWNED_BY_ACTOR("error.content.article.already.owned.by.actor", 17036, ErrorHttpStatus.CONFLICT),
    INVALID_REVIEW_COMPLETION_DATA("error.content.article.review.completion.invalid.data", 17037, ErrorHttpStatus.BAD_REQUEST),
    INVALID_REVIEW_RESULT("error.content.article.review.result.invalid", 17038, ErrorHttpStatus.BAD_REQUEST),
    INVALID_REVIEW_WITHDRAWAL_DATA("error.content.article.review.withdrawal.invalid.data", 17039, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_SLUG_ALREADY_EXISTS("error.content.article.slug.already.exists", 17040, ErrorHttpStatus.CONFLICT),
    ARTICLE_NOT_FOUND("error.content.article.not.found", 17041, ErrorHttpStatus.NOT_FOUND),
    INVALID_ARTICLE_NEW_OWNER("error.content.article.new.owner.invalid", 17042, ErrorHttpStatus.BAD_REQUEST),
    ARTICLE_ARCHIVED("error.content.article.archived", 17043, ErrorHttpStatus.GONE),
    ARTICLE_VERSION_NOT_FOUND("error.content.article.version.not.found", 17044, ErrorHttpStatus.NOT_FOUND),

    INVALID_CATEGORY_NAME("error.content.category.name.invalid", 18000, ErrorHttpStatus.BAD_REQUEST),
    CATEGORY_ALREADY_INACTIVE("error.content.category.already.inactive", 18001, ErrorHttpStatus.CONFLICT),
    CATEGORY_ALREADY_ACTIVE("error.content.category.already.active", 18002, ErrorHttpStatus.CONFLICT),
    INVALID_CATEGORY_DATA("error.content.category.invalid.data", 18003, ErrorHttpStatus.BAD_REQUEST),
    INVALID_CATEGORY_STATUS("error.content.category.status.invalid", 18004, ErrorHttpStatus.BAD_REQUEST),
    CATEGORY_NAME_ALREADY_EXISTS("error.content.category.name.already.exists", 18005, ErrorHttpStatus.CONFLICT),
    CATEGORY_NOT_FOUND("error.content.category.not.found", 18006, ErrorHttpStatus.NOT_FOUND),
    CATEGORY_NOT_ACTIVE("error.content.category.not.active", 18007, ErrorHttpStatus.CONFLICT),

    INVALID_TOPIC_NAME("error.content.topic.name.invalid", 19000, ErrorHttpStatus.BAD_REQUEST),
    INVALID_TOPIC_CATEGORY("error.content.topic.category.invalid", 19001, ErrorHttpStatus.BAD_REQUEST),
    TOPIC_ALREADY_INACTIVE("error.content.topic.already.inactive", 19002, ErrorHttpStatus.CONFLICT),
    TOPIC_ALREADY_ACTIVE("error.content.topic.already.active", 19003, ErrorHttpStatus.CONFLICT),
    INVALID_TOPIC_DATA("error.content.topic.invalid.data", 19004, ErrorHttpStatus.BAD_REQUEST),
    INVALID_TOPIC_STATUS("error.content.topic.status.invalid", 19005, ErrorHttpStatus.BAD_REQUEST),
    TOPIC_NAME_ALREADY_EXISTS("error.content.topic.name.already.exists", 19006, ErrorHttpStatus.CONFLICT),
    TOPIC_NOT_FOUND("error.content.topic.not.found", 19007, ErrorHttpStatus.NOT_FOUND),
    TOPIC_NOT_ACTIVE("error.content.topic.not.active", 19008, ErrorHttpStatus.CONFLICT),
    TOPIC_NOT_BELONG_TO_CATEGORY("error.content.topic.not.belong.to.category", 19009, ErrorHttpStatus.BAD_REQUEST),

    CONTENT_FORBIDDEN_ACTION("error.content.forbidden.action", 20000, ErrorHttpStatus.FORBIDDEN),
    MEDIA_NOT_SUITABLE_FOR_COVER("error.content.media.not.suitable.for.cover", 20001, ErrorHttpStatus.BAD_REQUEST),

    ;

    private final String messageKey;
    private final int errorCode;
    private final ErrorHttpStatus httpStatus;

    ErrorCode(String messageKey, int errorCode, ErrorHttpStatus httpStatus) {
        this.messageKey = messageKey;
        this.errorCode = errorCode;
        this.httpStatus = httpStatus;
    }

}
